apiVersion: v1
kind: Pod
metadata:
  name: n1
  labels:
    name: nginx-p
spec:
  hostname: nginx
  #subdomain: acsa
  containers:
  - name: n1
    image: nginx
    ports:
      - containerPort: 80
        name: n1
