apiVersion: v1
kind: Pod
metadata:
  name: n2
  labels:
    name: nginx-p
spec:
  hostname: nginx2
  #subdomain: acsa
  containers:
  - name: n2
    image: nginx
    ports:
      - containerPort: 80
        name: n2