apiVersion: v1
kind: Pod
metadata:
  name: n3
  labels:
    name: n33
spec:
  initContainers:
    - name: init-n3
      image: nginx
  containers:
  - name: nginx
    #hostname: ubuntu1
    image: nginx
    ports:
      - containerPort: 80
        name: nginx-p
