apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  #type: ClusterIP # Si no tiene ésta etiqueta la toma igual por defecto.
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend

