apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  containers:
    - env:
        - name: NODE_ENV
          value: production
        - name: REGISTRY_DOMAIN
        - name: REGISTRY_HOST
          value: registry:5000
        - name: REGISTRY_SSL
        - name: REGISTRY_STORAGE_DELETE_ENABLED
      image: jc21/registry-ui
      name: ui
      resources: {}
  restartPolicy: OnFailure
status: {}
